# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: Buildjob
    steps:
    - bash: echo "Do the Build"
- stage: DevDeploy
  jobs:
  - deployment: DevDeployjob 
    environment:Dev
      runOnce:
        steps:
          - script: echo "Deploy to Dev"
- stage: QADeploy
  jobs:
  - deployment: DevQADeploy
    environment:QA
      runOnce:
          steps:
          - script: echo "Deploy to QA"
